### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by JakubMazur** [vimeo/VimeoNetworking#116]
Hi, can you provide Carthage support for this library? For now I got an error:

```
*** Skipped building VimeoNetworking due to the error:
Dependency "VimeoNetworking" has no shared framework schemes for any of the platforms: iOS
```

https://github.com/Carthage/Carthage#supporting-carthage-for-your-framework

```
Carthage only officially supports dynamic frameworks. Dynamic frameworks can be used on any version of OS X, but only on iOS 8 or later.

Because Carthage has no centralized package list, and no project specification format, most frameworks should build automatically.

The specific requirements of any framework project are listed below.
```

**Comment by jasonhawkins** [comment]
Hello! I know it's been forever but I wanted to give an update on this. We've got a branch up that should allow you to add VimeoNetworking to a Cartfile. 

The branch is `tech/add-carthage-support` and there's a PR [here](https://github.com/vimeo/VimeoNetworking/pull/174). I can't say for sure when this will get merged, but hopefully this helps if you need Carthage support _now_.  

In your Cartfile you'll need to add version 3.1.0 of AFNetworking, in addition to VimeoNetworking:

```
github "Vimeo/VimeoNetworking" "tech/add-carthage-support"
github "AFNetworking/AFNetworking" == 3.1.0
```
I'm going to go ahead and close this issue but feel free to comment on the PR. We've got some other, bigger fish to fry, but improved compatibility with dependency managers is part of the plan 👍🏼
