### ISSUE TITLE
Doesn't install via CocoaPods

### ISSUE THREAD

**Issue by shalamowww** [vimeo/VimeoNetworking#118]
[!] Unable to find a specification for `VimeoNetworking (= 1.0)`

**Comment by jasonhawkins** [comment]
Hi @shalamowww, thanks for creating an issue. Fixing this is high on the list of priorities, but comes after full Swift 3 support. We currently have a work-in-progress version of VimeoNetworking with Swift 3 on our `develop` branch. We're closing in on a final release and that version will include CocoaPods support. 

I don't have a date for you, but this is under active development and very important to us internally as well. I'm going to close the issue for now, but a release with CocoaPods support is on its way.

**Comment by hahuja** [comment]
Hi, this issue still exists.

PFA Screenshot,
![screen shot 2018-02-20 at 4 33 29 pm](https://user-images.githubusercontent.com/30920058/36420736-f88d071c-165b-11e8-93ef-9eec94364845.png)
