### ISSUE TITLE
Instructions advise to install via pod file however this method fails and there are no other instructions around which files are needed

### ISSUE THREAD

**Issue by russnettle** [vimeo/VimeoNetworking#163]
"To get started integrating VimeoNetworking, add the following lines to your Podfile and run pod install:"

This fails

There are no other instructions on which files are needed - please could you update the read me?

**Comment by lloydroc** [comment]
OK I got it to work. What they meant by the instructions was in your main XCode project create a folder called `Submodules`. Clone the VimeoNetworking project into the `Submodules` folder. Then change

```
pod 'VimeoNetworking', './Submodules/VimeoNetworking'
```

To this:
```
pod 'VimeoNetworking', :path => './Submodules/VimeoNetworking'
```

**Comment by jasonhawkins** [comment]
Hi there, sorry for the confusion. @lloydroc is right.

We're working on re-writing our docs and have set up a work-in-progress guide here. Try it out and let us know if you run into any problems.

https://paper.dropbox.com/doc/Getting-Started-with-Submodules-as-Development-Pods-yRpNbPxIOjzGlcEbecuOC

**Comment by jasonhawkins** [comment]
I'm going to go ahead and close this for now. But let us know you need more help getting set up, or if those instructions aren't clear enough 👍
