### ISSUE TITLE
ArgumentError - Illformed requirement `"./Submodules/VimeoNetworking"`

### ISSUE THREAD

**Issue by duraiganesh0** [vimeo/VimeoNetworking#171]
I am getting this error 

> ArgumentError - Illformed requirement

 `"./Submodules/VimeoNetworking"`  when i run pod install. can anyone help me to resolve this problem?

**Comment by jasonhawkins** [comment]
Hi there, sorry for the confusion. 

We're working on a few things at once right now, including our docs. We do have a work-in-progress document set up that might be helpful though! Try following the steps in here and let us know if you run into any trouble: 

https://paper.dropbox.com/doc/Getting-Started-with-Submodules-as-Development-Pods-yRpNbPxIOjzGlcEbecuOC

**Comment by jasonhawkins** [comment]
I'm going to close this issue, but don't hesitate to let us know if you still need help getting set up.
