### ISSUE TITLE
Get private videos

### ISSUE THREAD

**Issue by jvsl** [vimeo/VimeoNetworking#190]
I have a private vdeo and I want to get it, but always receive Request failed: unauthorized (401) as redponse. I have client Id, client secret and access token. What am I doing wrong?

func configVimeoApp() {
        let clienId = "xxxx";
        let clientSecret = "xxx"
        let appConfiguration = AppConfiguration(
        clientIdentifier: clienId,
        clientSecret: clientSecret,
        scopes: [.Private], keychainService: "")
        
        let vimeoClient = VimeoClient(appConfiguration: appConfiguration)
        
        let authenticationController = AuthenticationController(client: vimeoClient, appConfiguration: appConfiguration)
        authenticationController.accessToken(token: "xxxxx") { result in
            switch result
            {
            case .success(let result):
                print("authenticated successfully: \(result)")
            case .failure(let error):
                print("failure authenticating: \(error)")
            }
        }
        
        let videoRequest = Request<VIMVideo>(path: "/videos/236223517")
        vimeoClient.request(videoRequest) { result in
            switch result {
                case .success(let response):
                    let video: VIMVideo = response.model
                    print("retrieved video: \(video)")
                case .failure(let error):
                    print("error retrieving video: \(error)")
                }
        }

    }

**Comment by jasonhawkins** [comment]
Hey, @jvsl. 

If the code in your app is executing exactly as you have it here, your request for the video object will actually kick off _before your auth request finishes_. You could try putting the video request under the `success` case where you currently have `print("authenticated successfully: \(result)")`. Or connect the request to another action, like tapping a cell.

But also, keep in mind that only Pro members can access their own video files in this way. So while you should have access to the video object, and see most of the data associated with the video, accessing the files required for playback requires Pro membership.

I hope this helps.

**Comment by jvsl** [comment]
Omg. Of course it's happen. It's asynchronous. Mad bad. Thanks.
