### ISSUE TITLE
Swift 3.2 / 4.0

### ISSUE THREAD

**Issue by JakeAtArtamata** [vimeo/VimeoNetworking#191]
Can you please update us on plans to support Swift 3.2 or Swift 4 so that we are able to use Vimeo on Xcode 9.

**Comment by ModPilot** [comment]
+1

**Comment by dougamos** [comment]
For me it works with swift 3.2.  I'm on develop branch. Make sure you project is set to use Swift 3.2 (Build Settings > Swift Language Version -> Swift 3.2) and that the pods are using Swift 3.2. This can be done by adding the following code to the end of your Podfile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.2'
        end
    end
end
```

**Comment by jasonhawkins** [comment]
@JakeAtArtamata, @ModPilot, @dougamos Hey folks, we don't have a PR up yet but I've got a branch that includes Swift 4 / Xcode 9 support: `tech/swift-4-support`. It should also help resolve a bunch of build warnings. We'll try to get that merged into `develop` soon but I hope it helps if you need better Xcode 9 / Swift 4 support right away. 

If you run into any issues definitely leave a comment. I'll leave this issue open until that PR is up.

**Comment by jasonhawkins** [comment]
In case you missed it, we tagged a release that includes Swift 4 support: https://github.com/vimeo/VimeoNetworking/releases/tag/3.1.0 🚀

We're still working on things, but hopefully this helps. It's been a long, long, lonnnng time coming.
