### ISSUE TITLE
How to get Albums?

### ISSUE THREAD

**Issue by kutakmir** [vimeo/VimeoNetworking#204]
The latest version's model doesn't include Album - what should I use to get albums? Thank you!

**Comment by kutakmir** [comment]
ok, it is not there yet, I created a Pull request:
https://github.com/vimeo/VimeoNetworking/pull/205

**Comment by jvcleave** [comment]
Any updates on this?

**Comment by jvcleave** [comment]
For anyone else trying to use this with cocoapods:
I was able to use this PR by adding the changes manually but they didn't show up until I ran `pod update`

I also had to chop of the first / in the `VIMAlbum.uri` object in order to make it compatible for further requests

**Comment by jasonhawkins** [comment]
@jvcleave Ah gotcha, do you usually use Submodules or Carthage or something like that instead?

If you wanted to use CocoaPods you could set up a Podfile from scratch using this as a starting point:

```Ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

# You can change this to whatever platform and OS version you need. VimeoNetworking supports iOS 8+ and tvOS 9+.
platform :ios, '9.0'

# Don't forget to relace with your target name here.
target 'YourAppTarget' do
    # Ideally you'd want to point to a version number like this:
    # pod 'VimeoNetworking', '3.3.1'

    # But to point to our feature branch you can do this:
    pod 'VimeoNetworking', :git => 'git@github.com:vimeo/VimeoNetworking.git', :branch => 'feature/vim-6641-albums-phase-one'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|

        # VimeoNetworking hasn't been updated for Swift 4.2 yet :(
        if target.name == 'VimeoNetworking'
            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '4.0'
            end
        end
    end
end
```

**Comment by jasonhawkins** [comment]
@kutakmir @jvcleave I know it's been a long, long time coming, but the albums work has been merged into our `develop` branch. We'll be working to get this behind an actual release version number soon, but hopefully this is helpful in the meantime. 

I'm going to close this issue but feel free to open another if you have any questions or comments. Thanks for your patience 🎉
