### ISSUE TITLE
Can't access private videos.

### ISSUE THREAD

**Issue by jyaunches** [vimeo/VimeoNetworking#207]
HI there! So, I'm using the swift 4.0 branch. Authentication went well.

I've found that I'm only able to access the public videos for this account. Here's a screen shot of the example code running from your README.. and the video detail page from the site showing the video is set to private.

(And the breakpoint showing the error.. it's a 404 NOT FOUND)

![screen shot 2018-01-19 at 7 52 08 pm](https://user-images.githubusercontent.com/372490/35177996-bdd15654-fd52-11e7-8796-9deca5adfc40.png)

Here's what happens after I change the video to be public.. It begins to start being returned.

![screen shot 2018-01-19 at 7 53 15 pm](https://user-images.githubusercontent.com/372490/35178006-d45d8a1e-fd52-11e7-833f-11a25a5754f4.png)

I suppose I am on a development branch of a git submodule. Kind of makes me nervous to think about using this anyway... What is the timeline for a sort of stable release?

**Comment by rslonik** [comment]
Hey @ jyaunches are you using the `develop` with Swift 4 and Xcode 9?

I tried to use `tech/swift-4-support` and `develop` without success. :(

I tried installing dragging files to my project and the clone and pod instructed in the Readme. None methods helped.

If you can tell me how you got it working I'll be grateful.

**Comment by pchelnikov** [comment]
I have the same issue (404 in response).
Any ideas?
@jasonhawkins @jenniferlim @ghking

**Comment by bclark8923** [comment]
Any update here?

**Comment by rpassis** [comment]
Hi everyone, 

Firstly apologies for taking so long to respond to this!

We just released a new version of the framework that should handle the issue with private videos returning 404. You can check it out here https://github.com/vimeo/VimeoNetworking/releases/tag/3.4.0

Rog
