### ISSUE TITLE
Can't get video_files

### ISSUE THREAD

**Issue by rslonik** [vimeo/VimeoNetworking#215]
Hello,

I'm testing this API but can't get the video files. 

I intend to download the files to permanently cache some videos in my APP (I'm testing with my own token and my own video, via "Lightweight auth use informed in the Readme"). 

I can get the user, the video (thumbs, names, etc). But can't find a way to retrieve the video files.

I need to be PRO user to access the video files?

I need to use PlayerKit to achieve this?

**Comment by nagueva** [comment]
Any news on this topic? I'm also having problems trying to get video files. ):

**Comment by oNguyenNgocBan** [comment]
I having the same problem. The token created by Login Authentication from my app can't get video files too. (I tested with token created by other apps, it can get video files)

**Comment by ChrisBGriffith** [comment]
I'm also having this issue. I have upgraded my account to pro, but the files array on the VIMVideo object is nil.

**Comment by jasonhawkins** [comment]
Hey everybody, sorry it took so long for a response here.

You're right that you need to be a Pro member to get access to your own video URLs, and you'll need to [register as a parter](https://www.vimeopartnernetwork.com) to get access to other people's Video URLs.

@ChrisBGriffith, are you still having a problem with this? My gut says you may need to generate a new access token after upgrading your account. But if you've tried that, or you're still unable to access the `download` array, let me know.

cc/ @rslonik, @nagueva, @prathamsalawkar, @oNguyenNgocBan

**Comment by jasonhawkins** [comment]
I'm going to go ahead and close out this issue, but feel free to open another issue if you run into any trouble 👍
