### ISSUE TITLE
Getting error while installing pod for VimeoNetworking

### ISSUE THREAD

**Issue by siddheshbhide** [vimeo/VimeoNetworking#247]
getting this error while pod update
No podspec found for `VimeoNetworking` in `./Submodules/VimeoNetworking`

**Comment by jasonhawkins** [comment]
Hey @siddheshbhide, were you able to use VimeoNetworking previously? Or is this the first time you've tried adding it to your project? If it's the latter, take a look at [this document](https://paper.dropbox.com/doc/Getting-Started-with-Submodules-as-Development-Pods--AICxYP0mYoJMSHUD_~M530BdAg-yRpNbPxIOjzGlcEbecuOC) which might help get you set up.

Let me know if you're still having trouble though 👍

**Comment by thanhnv58it** [comment]
your document save my day 👌

**Comment by jasonhawkins** [comment]
@thanhnv58it, awesome I'm glad to hear it 🎉

**Comment by jasonhawkins** [comment]
I'm going to close this out, but let me know if you have any other issues, @siddheshbhide.

**Comment by pawansn** [comment]
Any other way to install VimeoSDk in iOS?

**Comment by jasonhawkins** [comment]
@pawansn Yes! Our latest release is version 3.3.0 and can be installed by adding this to your project's Podfile:
```Ruby
pod 'VimeoNetworking', '3.3.0'
``` 


https://cocoapods.org/pods/VimeoNetworking

**Comment by pawansn** [comment]
@jasonhawkins nice to hear that
Thanks
