### ISSUE TITLE
Cannot retrieve video link

### ISSUE THREAD

**Issue by MaXiao** [vimeo/VimeoNetworking#256]
I'm using a `Pro` account, and try to retrieve the link of one of my own video, so I can play it in my app. I got the video object, but the `files` property is always `nil`.

I suspect it may related to the `scopes` declaration, but `Scope` enum doesn't have a `video_files` value.

I also tried to make that call on API playground, the response payload doesn't have a `files` field, or anything looks like a video file link. 

I do see the `embed` data, but `VIMVideo` doesn't expose that. 

Any suggestion on what can I do to get the video link?

**Comment by bryantjustin** [comment]
Did you upgrade to a PRO after your app's token was created? If so, have you tried creating a new token yet? This could also explain why the `files` property isn't being returned.

**Comment by MaXiao** [comment]
Never mind, there was a timing issue with the access token authentication request and the data request. Now I can see the `files` after resolving the issue.
