### ISSUE TITLE
Is VideoFiles still a supported Scope?

### ISSUE THREAD

**Issue by ugowe** [vimeo/VimeoNetworking#259]
I have a Pro account and I'm trying to play videos from the `files` array as mentioned here: https://github.com/vimeo/PlayerKit/issues/29

However, `VideoFiles` seems to no longer be a case for the Scope enum.

Is there another way to access that `link` URL in the `files` array?

![screen shot 2018-08-23 at 2 46 47 pm](https://user-images.githubusercontent.com/16910028/44674516-c01fe000-a9fb-11e8-9a94-259a8aeec945.png)

**Comment by ugowe** [comment]
@jasonhawkins @Jumhyn

**Comment by jasonhawkins** [comment]
Hey @ugowe, I know it's been a long, long time but I have an update on this! 

We just merged a pull request that [adds the `video_files` scope](https://github.com/vimeo/VimeoNetworking/pull/308) which should make this kind of thing much easier in the future. I know this issue has been open for a very long time at this point, but I hope it's helpful.
