### ISSUE TITLE
Stop linking to this if it's deprecated?

### ISSUE THREAD

**Issue by hawflakes** [vimeo/VimeoNetworking#262]
https://developer.vimeo.com/api/reference

links to this repo. But the repo says it's deprecated and to go to https://github.com/vimeo/PlayerKit instead. Can you update the docs?

**Comment by hawflakes** [comment]
Whoops. I filed against the wrong repo. It was meant for https://github.com/vimeo/VIMVideoPlayer/issues
https://developer.vimeo.com/api/libraries 

I'll file it there. Sorry about that.

**Comment by hawflakes** [comment]
Opened up an issue here: https://github.com/vimeo/VIMVideoPlayer/issues/73

**Comment by jasonhawkins** [comment]
Ah, gotcha. Thanks for updating the issue! I'll see what we can do about getting that stuff changed.
