### ISSUE TITLE
cannot get authorize only with access token

### ISSUE THREAD

**Issue by PavelKatunin** [vimeo/VimeoNetworking#288]
The following example is wrong, there is no initializer without AppConfiguration.

let authenticationController = AuthenticationController(client: vimeoClient)
authenticationController.accessToken("your_access_tocken") { result in
    switch result
    {
        case .Success(let account):
            print("authenticated successfully: \(account)")
        case .Failure(let error):
           print("failure authenticating: \(error)")
    }
}

In Android I need only an access token to get video streams, but in iOS there is an issue.

How can I download URL stream by video Id on iOS ?

Thanks!

**Comment by PavelKatunin** [comment]
Now I'm using all credentials and it crashes

AppConfiguration

**Comment by rpassis** [comment]
Hi @PavelKatunin I am going to close this for now but please feel free to open a new issue if you are still having issues, including the steps to reproduce your problem. Thanks!
