### ISSUE TITLE
Full url to video is broken in the latest versions. Pro account.

### ISSUE THREAD

**Issue by Vitaliy-Sh** [vimeo/VimeoNetworking#290]
This problem has already been opened many times, but looks like it is not resolved yet!

We want to get full url to video files, but in the last versions we cannot do this - "files" array is empty in the received object.
We can get files array not empty only in version 3.1.0. Any version newer than that returns nil.
New version 3.3.1 has been released recently. But the fields array is still nil.

We have a paid Pro account.
We have created tokens after subscribing to Pro.
We have recreated tokens later.

Steps to reproduce:

Create Single View App project.
Clone VimeoNetworking to project directory:
`git clone https://github.com/vimeo/VimeoNetworking`
Add to Podfile pod, referencing VimeoNetworking from folder (due to version 3.1.0 is not available in CocoaPods repository):
`pod 'VimeoNetworking', :path => './VimeoNetworking'"`
Install pods:
`pod install`

Add this file to project:
`import Foundation
import VimeoNetworking

class VimeoService {
    static let shared = VimeoService()
    
    private let appConfiguration: AppConfiguration
    private let vimeoClient: VimeoClient
    
    private init() {
        appConfiguration = AppConfiguration(
            clientIdentifier: VimeoKeys.clientId,
            clientSecret: VimeoKeys.clientSecret,
            scopes: [.Private],
            keychainService: "\(Bundle.main.bundleIdentifier ?? "").vimeoKeychainService")
        
        vimeoClient = VimeoClient(appConfiguration: appConfiguration)
    }
    
    func test() {
        auth {
            self.request(videoId: VimeoKeys.testVideoId, completion: { (vimVideo) in
                print(vimVideo.files)
                print()
            })
        }
    }
    
    func auth(completion: @escaping () -> Void) {
        let authController = AuthenticationController(client: vimeoClient, appConfiguration: appConfiguration)
        
        authController.accessToken(token: VimeoKeys.token) { (result) in
            switch result {
            case .success(let account):
                assert(account.user?.accountType == VIMUserAccountType.pro)
                completion()
            case .failure(let nsError):
                print(nsError)
            }
        }
    }
    
    func request(videoId: String, completion: @escaping (VIMVideo) -> Void) {
        let videoRequest = VideoRequest(path: "/videos/\(videoId)")
        let _ = vimeoClient.request(videoRequest) { (result) in
            switch result {
            case .success(let response):
                completion(response.model)
            case .failure(let nsError):
                print(nsError)
            }
        }
    }
}`

Add file with keys, which looks like this one:
`enum VimeoKeys {
    static let testVideoId = "<videoId>"
    static let token = "<your token>"
    static let clientId = "<your client id>"
    static let clientSecret = "<your client secret>"
}`

Call VimeoService.shared.test() in AppDelegate didFinishLaunchingWithOptions method.

Set 3.3.1 version:
cd VimeoNetworking
git checkout 3.3.1
cd ..
pod install

Build and run the App
vimVideo.files will be nil

Set 3.1.0 version:
cd VimeoNetworking
git checkout 3.1.0
cd ..
pod install

Build and run the App (you may need to Clean Build Folder and Derived Data)
vimVideo.files will have some VIMVideoFile objects, every contains the "link" property with full url to video file for streaming.

**Comment by rpassis** [comment]
Hi @Vitaliy-Sh , 

Firstly apologies for taking so long to respond to this!

We just released a new version of the framework that may address the issue you are having. You can check it out here https://github.com/vimeo/VimeoNetworking/releases/tag/3.4.0

Once you had a chance to test it, please let us know if it is still a problem and I'll work with you to resolve it.

Thanks!
Rog
