### ISSUE TITLE
Private Video 404 Error

### ISSUE THREAD

**Issue by connorb645** [vimeo/VimeoNetworking#292]
Hi,

Having obtained a premium Vimeo account, I would like to be able to use the provided Video API in order to access specific Private videos.
I have successfully authenticated the application with the premium account using the following code: 

<img width="592" alt="screenshot 2019-01-22 at 11 47 37" src="https://user-images.githubusercontent.com/18633525/51533708-8ed8fe00-1e3b-11e9-86a7-f355fdbf3b85.png">

Upon successful authentication I am making a call to request a specific private video via the video ID, using the following code:

<img width="471" alt="screenshot 2019-01-22 at 11 47 46" src="https://user-images.githubusercontent.com/18633525/51533722-9b5d5680-1e3b-11e9-960d-5136034a8e2b.png">

The response I receive is a 404 - not found.

When modifying the specified video to “Public”, I am able to use the above code to access all necessary information about the video without receiving a 404 - not found error.

Any help on this situation would be greatly appreciated.

**Comment by rpassis** [comment]
Hi @connorb645, 

Firstly apologies for taking so long to respond to this!

We just released a new version of the framework that should handle the issue with private videos returning 404. You can check it out here https://github.com/vimeo/VimeoNetworking/releases/tag/3.4.0

Rog
