### ISSUE TITLE
VimVideo.Files come as nil for version 3.3.1

### ISSUE THREAD

**Issue by prathamsalawkar** [vimeo/VimeoNetworking#306]
In VIMVideo objects Files are coming as nil. In version 3.0.1 it is working fine but in version 3.3.1 which is necessary for XCode 10.2 and swift version upgrade it is failing. I am not sure where the issue is, Please help me in this, Thanks.

**Comment by jasonhawkins** [comment]
@prathamsalawkar We just merged a pull request that[ adds the `VideoFiles` scope to our `Scope` enum](https://github.com/vimeo/VimeoNetworking/pull/308). If you have a Pro account you should be able to combine this with the `Private` scope to access your video files. I hope this is helpful!
