### ISSUE TITLE
Getting private video files

### ISSUE THREAD

**Issue by ExtremeKaos** [vimeo/VimeoNetworking#320]
Hi , i'm unable to get the list of files from VIMVideo.

Have changed the scopes to    scopes: [.Public, .Private, .Interact,.VideoFiles] in authentication (authentication works right) ("video_files")

I can get video name strongSelf.videodir?.name , but when request strongSelf.videodir?.files is returning null.

I have a Pro account. This have been working until have upgraded to last version.

thanks in advance,

**Comment by ExtremeKaos** [comment]
Hi, i have generated a new token and now i'getting file list. 

The linkSecure property of video have a scope diferent, getting null...

Sorry :)

**Comment by rpassis** [comment]
Thanks @ExtremeKaos! 

It sounds like you have sorted it out so I am going to close this issue.

Please feel free to get in touch if you still need help!

Rog
