### ISSUE TITLE
Failed to build scheme (Carthage)

### ISSUE THREAD

**Issue by Vitalyz123** [vimeo/VimeoNetworking#328]
Hey everyone!

I'm trying to install framework with Carthage but it returns me an error:
Dependency "VimeoNetworking" has no shared framework schemes for any of the platforms: iOS

Can anyone help me please? Thanks!

**Comment by rpassis** [comment]
Hi @Vitalyz123 we recently merged Carthage support into the develop branch so can you please point your Cartfile to that branch instead of the release tag, and see if it fixes your issue? 

We will tag a new release for Carthage support soon. 

Thanks
Rog

**Comment by Vitalyz123** [comment]
@rpassis hey, thank for the quick reply

I've tried to put github "vimeo/VimeoNetworking" "develop"
But still it returns me an error during building scheme
Build Failed
	Task failed with exit code 65: ...

**Comment by rpassis** [comment]
Hey @Vitalyz123 I just tried and have been able to reproduce this.

This is a regression from previous behavior, and we will work on a fix shortly.

I'll ping you here again as soon as it is fixed and merged back into develop.

**Comment by Vitalyz123** [comment]
@rpassis thank you!

**Comment by rpassis** [comment]
@Vitalyz123 Thanks again for raising this issue, I created PR #329 which is currently waiting for someone from our team to review but it should be merged into develop shortly. In the meantime please feel free to point your Cartfile to this branch and let us know if it fixes the error you were seeing!

**Comment by Vitalyz123** [comment]
@rpassis Thank you for taking care of it :) It seems to be okay now!

**Comment by rpassis** [comment]
Awesome, thanks for letting me know! 

I'm going to leave this issue open until or PR is merged.

Rog

**Comment by Vitalyz123** [comment]
@rpassis Actually there is an issue. I don't know if I should raise another ticket but when I'm trying to launch my app it crashes with:

dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
  Referenced from: ../Frameworks/VimeoNetworking.framework/VimeoNetworking
  Reason: image not found

Do you know what can be reason for that? Thanks!

**Comment by rpassis** [comment]
`VimeoNetworking` currently depends on `AFNetworking` so you also to add that as a Carthage dependency on your main project as well.

There should be a copy of the framework already under `Carthage/Build/[PLATFORM_NAME]` so all you need to do is follow the Carthage integration steps as described [here](https://github.com/Carthage/Carthage#adding-frameworks-to-an-application)

**Comment by rpassis** [comment]
Here's a quick integration sample in case you want to have a look - https://github.com/rpassis/VIMNetworkingCarthageSample

**Comment by Vitalyz123** [comment]
@rpassis Adding AFNetworking.framework did the trick :) Thanks again for your help!

**Comment by rpassis** [comment]
Hi @Vitalyz123 FYI this has been merged into develop and tagged with `4.1.0-alpha.1` for now.
