### ISSUE TITLE
iOS Example app not compiling due to minimum deployment target

### ISSUE THREAD

**Issue by DavidBemerguy** [vimeo/VimeoNetworking#335]
Compiling the iOS Example leads to compile error:
Compiling for iOS 9.0, but module 'VimeoNetworking' has a minimum deployment target of iOS 10.3: /Users/davidbemerguy/Library/Developer/Xcode/DerivedData/VimeoNetworking-ehdrjazwcfjehebpihhnbpxkhzlm/Build/Products/Debug-iphonesimulator/VimeoNetworking.framework/Modules/VimeoNetworking.swiftmodule/x86_64.swiftmodule

**Comment by rpassis** [comment]
Fixed in #339
