### ISSUE TITLE
Carthage support

### ISSUE THREAD

**Issue by DavidBemerguy** [vimeo/VimeoNetworking#344]
I am adding 
github "vimeo/VimeoNetworking" to my Cartfile
And then running
carthage update VimeoNetworking --platform io
And receive the error:
Dependency "VimeoNetworking" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/vimeo/VimeoNetworking/issues/new

**Comment by rpassis** [comment]
Hi David can you please try to point your Cartfile to the develop branch and let me know if that makes a difference? 

We have made some changes to Carthage integration that are not in master or tagged yet.

**Comment by rpassis** [comment]
Just as a quick update we released 5.0.0 today so you can now point your Cartfile directly to that version.

**Comment by rpassis** [comment]
Closing this, please let me know if this is still an issue.
