### ISSUE TITLE
Can't access to "files" array in response /video/\(id)

### ISSUE THREAD

**Issue by NullGraviton** [vimeo/VimeoNetworking#361]
Hi.
I need to implement Vimeo's videos playback functionality in my application. 
Vimeo account: "live premium",
VimeoNetwork library (release 4.0.0).
iOS 13.1
Xcode 11.0

Here is code:
```Swift
class VimeoService {
    var authController:AuthenticationController?

    let appConf = AppConfiguration(clientIdentifier: "blablabla", clientSecret: "blablablablablablablabla", scopes: [.Private, .Public, .Upload, .Interact,.VideoFiles], keychainService: "KeychainServiceVimeo")
    
    let backgroundSessionIdentifier = "vimeoBackgroundSessionIdentifier"

    let client:VimeoClient = VimeoClient.sharedClient
    var user:VIMAccount?
    
    init() {
        self.authController = AuthenticationController(client: client, appConfiguration: self.client.configuration ?? appConf, configureSessionManagerBlock: nil)

        if self.user == nil {
            self.authController?.clientCredentialsGrant(completion: {[weak self] (result) in

                switch result {
                case .success(result: let account):
                    print(account)
                    self?.user = account
                case .failure(error: let error):
                    print(error)
                }
            })
        }
    }
    
    func getVideo(id:String, completion:@escaping((VIMVideoFile?) -> ())) {
        let videoFiles = VideoRequest.videoRequest(forVideoURI: "/videos/"+id)
        _ = self.client.request(videoFiles) { (result) in
                switch result {
                case .success(result: let videoInf):
                    print(videoInf.model.files)
                    completion(videoInf.model.files?.last as? VIMVideoFile)
                case .failure(error: let error):
                    print(error)
                }
            }
    }
}
   ```

As result I got all information about videoFile, beside the "files" array.

**Comment by rpassis** [comment]
Hi @Crissfade thanks for opening this issue!

Are you able to confirm that the video you are trying to fetch is owned by the authenticated account?

**Comment by NullGraviton** [comment]
> Hi @Crissfade thanks for opening this issue!
> 
> Are you able to confirm that the video you are trying to fetch is owned by the authenticated account?

Yes. I confirm that I'm trying to fetch video files owned by the authenticated account. 
And even more, I found interesting case: 
If I'm trying to fetch video file data, using "Bearer " from response of clientId and clientSecret authentication method with "scope = [.public, .private, .videoFIles]", I did not received any file.
But if I'm trying to fetch video file data, using "Bearer " from developer panel at "developer.vimeo.com" where I can generate Bearer using "scope = [.public, .private, .videoFIles]", I received all needed information, without any problems.

**Comment by djanaviciusito** [comment]
Hi @Crissfade, I had the same issue. What I did to make it work: 
- added video_files scope to my app accessToken
- changed keychainServiceKey to new one when generating AppConfiguration

**Comment by NullGraviton** [comment]
Hi @djanaviciusito . I was try to do the same, but no positive result. Unfortunately "changed keychainServiceKey to new one when generating AppConfiguration" doesn't helped also. The only way to get VN (VimeoNetworking) work is generate "AccessToken" at dev panel, as I described. I will try your solution later, with an own demo app. Thanks for helping.

**Comment by rpassis** [comment]
Hi @Crissfade have you been able to solve this issue?

**Comment by Hurricane1111** [comment]
> Hi @Crissfade have you been able to solve this issue?

No. Actually I left generated access token as I described early. Do you have any news about this?

**Comment by rpassis** [comment]
Just to avoid any confusion @Hurricane1111, are you the same user as @Crissfade or are you saying to have a similar issue?

**Comment by Hurricane1111** [comment]
> Just to avoid any confusion @Hurricane1111, are you the same user as @Crissfade or are you saying to have a similar issue?

Oh, sorry to confused you. Yes. I am the same user.

**Comment by rpassis** [comment]
Hi @Crissfade thanks for confirming!

I noticed that you are using the `clientCredentialsGrant` credentials method of the `AuthenticationController`. Note that what this returns you is an unauthenticated user so you will *not* have access to the **Video Files** scope as per the documentation:

> Execute a client credentials grant request.  This type of authentication allows access to public content on Vimeo.

For that you will need to authenticate first, then request the video(s) (or alternatively use an authenticated access token as you've already figured out).

I hope that helps but please feel free to get in touch if you have any questions!

**Comment by NullGraviton** [comment]
> Hi @Crissfade thanks for confirming!
> 
> I noticed that you are using the `clientCredentialsGrant` credentials method of the `AuthenticationController`. Note that what this returns you is an unauthenticated user so you will _not_ have access to the **Video Files** scope as per the documentation:
> 
> > Execute a client credentials grant request.  This type of authentication allows access to public content on Vimeo.
> 
> For that you will need to authenticate first, then request the video(s) (or alternatively use an authenticated access token as you've already figured out).
> 
> I hope that helps but please feel free to get in touch if you have any questions!

@rpassis Thanx for helping me. I leave this as it for now. 
I'm closing this issue.
