### ISSUE TITLE
ITMS-90809: Deprecated API Usage

### ISSUE THREAD

**Issue by dbyst** [vimeo/VimeoNetworking#374]
Hi guys. 
My app uses VimeoNetworking which works great. Thank you.
However, when uploading app to appstoreconnect, I'm receiving message from apple:
ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

This message appears because VimeoNetworking uses AFNetworking. And AFNetworking use UIWebView APIs.

Do you know if AFNetworking already removed or going to remove deprecated API ?
Or maybe you plan to replace AFNetworking ?
Otherwise, application will not be accepted by AppStore.

**Comment by rpassis** [comment]
Hi @dbyst,

Thanks for opening this issue!

Could you please let me know what version of `VimeoNetworking` you are currently using? We have a fix for this that has already been merged into develop but depending on the version you are using there may be multiple breaking changes in the API as we are working towards version 5.0 later in the year.

FWIW it doesn't look like `AFNetworking` is receiving a lot of support from maintainers and we are taking steps to replace it in the future.

I am also looking into the possibility of releasing an update to `3.4` and `4.0` that removes the UIWebView extension of `AFNetworking`.

Thanks!
Rog

**Comment by dbyst** [comment]
Hi @rpassis.
Thanks for response.
I'm using version 4.0.

**Comment by ihnatmoisieiev** [comment]
Hello, Vimeo Team!

First of all, thanks for great library.

When we could expect a new release fixing the issue?

**Comment by rpassis** [comment]
Hi there 

We tagged an update to 4.0 to 4.1.0 here https://github.com/vimeo/VimeoNetworking/releases/tag/4.1.0. This will be published to cocoapods today. 

Let us know how you go after updating and feel free to get in touch if you have any questions.

**Comment by ihnatmoisieiev** [comment]
@rpassis thank you for quick response and action!

**Comment by rpassis** [comment]
Just a quick update - `4.1.0` has been [published](https://cocoapods.org/pods/VimeoNetworking) to Cocoapods as of this morning.
