### ISSUE TITLE
Generating Access Token through API with scope to private & video_files

### ISSUE THREAD

**Issue by tusharquantsapp** [vimeo/VimeoNetworking#375]
I have a PRO account and I have few video files which are "private" or "hide from vimeo". I need to get the **video_files** value (for streaming url) for these videos with the access token generated through API but I do not wish to use client authentication to view the private/hidden videos in the app. Basically I don't want the user to log in to view my private/hidden videos. Can I generate the access token with private/video_files scope? I don't want to keep the access token anywhere in my app.

**Comment by rpassis** [comment]
Hi @tusharquantsapp,

To be able to query for those `video_files` you will need some form of authentication. If requiring client authentication is not an option, the only alternative is to use an access token.

Where you do that is completely up to you though.

You could - for example - have your backend call the API, parse the `video_files` and expose them via an access point that the app can query. This would ensure your access token never leaves your owned infrastructure but then you will need to deal with the problem of how to securily expose the endpoint that serves the `video_files` URLs.

I hope that makes sense but please feel free to get in touch if you have more questions!

**Comment by rpassis** [comment]
Closing this for now - please feel free to reopen if you still need help.
