### ISSUE TITLE
Objective C

### ISSUE THREAD

**Issue by pangia** [vimeo/VimeoNetworking#412]
Are there any examples of how to use the SDK in an Objective C app?

**Comment by rpassis** [comment]
Hi there,

The library does not officially support Objective-C. 

It **may** work but we make no guarantees, nor provide any support for it.

Thanks for reaching out!

Rog

**Comment by pangia** [comment]
We have a vimeo pro account, and would like to use Vimeo in one of our larger apps. Is there any suggestion for implementation in a objc project?

**Comment by vvdodiya** [comment]
Hello I want to integrate in objective c project. please help me.

**Comment by vvdodiya** [comment]
Hello @pangia  @rpassis 
I want to integrate VimeoNetworking in the Objective c project. Is there any suggestion for improvement in objective c Project. Please help.
