### ISSUE TITLE
How do you play a video after you get it? 

### ISSUE THREAD

**Issue by bogdanpralea** [vimeo/VimeoNetworking#420]
Hello, 
so I am able to get the videos from VimeoNetworking, but I don't know how to play them using the PlayerKit.

Help? 
Thanks

**Comment by bogdanpralea** [comment]
Nevermind. I have found the answer in the closed issue.

**Comment by hiteshborse12** [comment]
@bogdanpralea  please share your answer. Once we got VIMVideo array how to play video?

**Comment by vvdodiya** [comment]
@bogdanpralea  please share your answer. I got VIMVideo from VimeoNetworking but can not play it. please help

**Comment by bogdanpralea** [comment]
func playVideo(from urlString: String) {
        let player = AVPlayer(url: URL(string: urlString)!)
        let vc = AVPlayerViewController()
        vc.player = player
        
        self.present(vc, animated: true) {
            vc.player?.play()
        }
    }

**Comment by Shayila** [comment]
@bogdanpralea can you please share the url structure to play the vimeo video in playerkit.

**Comment by bogdanpralea** [comment]
> @bogdanpralea can you please share the url structure to play the vimeo video in playerkit.

As you can see above I haven't used the playerkit, I have used AVPlayerViewController

**Comment by Shayila** [comment]
@bogdanpralea "https://vimeo.com/{video-id}" this is the url structure i'm receiving. If try to play this in avplayer it's not working. Kindly suggest

**Comment by hiteshborse12** [comment]
@Shayila  & @vvdodiya Please share your code to get the video URL. Verify which premium account you are using. You will only be able to access your video files links with a PRO account .
[https://github.com/vimeo/VimeoNetworking/issues/426](url)
