### ISSUE TITLE
How to use in Objective-C?

### ISSUE THREAD

**Issue by swissdude** [vimeo/VimeoNetworking#433]
I have an Objective-c Project and am trying to use this Framework (and the VimeoUploader). Alas it's not working.

I'm using

#import <VimeoNetworking/VimeoNetworking.h>
#import <VimeoUpload/VimeoUpload-Swift.h>

But when I try to instantiate the classes, XCode doesn't recognize them.

I'm using cocoapods, btw and did add the Frameworks with it.

**Comment by rpassis** [comment]
Hi there,

Both libraries do not officially support Objective-C but you may have some luck by using:

```swift
@import VimeoNetworking
@import VimeoUpload
```

We make no guarantees that this will work and some of the public API may still be unavailable for use, but it is worth a shot.

Good luck!
Rog
