### ISSUE TITLE
Unable to find a specification for `VimeoNetworking`

### ISSUE THREAD

**Issue by geek1250** [vimeo/VimeoNetworking#52]
when using Pod, I got this error: "Unable to find a specification for `VimeoNetworking`"
in Podfile:
pod 'VimeoNetworking'

if in Podfile:
pod 'VimeoNetworking', '1.0'
the error is :
Analyzing dependencies
[!] Unable to find a specification for `VimeoNetworking (= 1.0)`

**Comment by FibonacciRedstone** [comment]
I've had this problem too, looked on cocoa pods and there is no 'pod' called VimeoNetworking. They need to fix this.

**Comment by geek1250** [comment]
Hi, thanks. I am try to using Objective-c library. But what should I set to
keychainService for VIMSessionConfiguration?
Thanks.

geek1250

**Comment by jasonhawkins** [comment]
Sorry for the slow response, but you're absolutely right that VimeoNetworking isn't part of the Cocoapods podspecs repo. Which means it cannot be installed with `pod install`. 

We have a list of things we're currently working through in VimeoNetworking, and part of that work is to make this a legitimate pod. And also to make sure our documentation is accurate 😬

In the meantime VimeoNetworking can only be added by dragging the files in manually.

**Comment by jsartain** [comment]
Would you please update your current README file to add this issue.    Thanks
