### ISSUE TITLE
Add Swift 3 Support

### ISSUE THREAD

**Issue by Addisonbean** [vimeo/VimeoNetworking#57]
Like the title says, Swift 3 support is currently missing from VimeoNetworking.

**Comment by Addisonbean** [comment]
Any update on this?

**Comment by TomCarey** [comment]
Agreed, desperately need swift 3 support

**Comment by muhammetkole** [comment]
Any update on swift 3?

**Comment by saiprasanna-palle** [comment]
Any estimated date by when the Swift 3 support will be out?

**Comment by mohaiminul-sust** [comment]
Desperately need this in swift 3. Any updates folks?

**Comment by shalamowww** [comment]
WIP?

**Comment by TomCarey** [comment]
Sorry everyone, I couldn't wait for Vimeo to update the library to swift 3 (which has been out for months) so I quickly converted it myself, https://github.com/TomCarey/VimeoNetworking Probably a bit of a hack in places but it seems to work for me.

**Comment by jasonhawkins** [comment]
Hi, everybody. It's been a long (lonng, lonnnng) time coming but we finally have a work-in-progress version of VimeoNetworking updated for Swift 3. 

This is not the final version as more work is needed (including fixing CocoaPods support, updating inline documentation & the readme, and more), but if you need Swift 3 support in your project today it might be worth checking out. Our `develop` branch should have what you need.

We're going to continue working on this and we really appreciate all of the support and comments from the community. Thanks, everybody. 

A production release with CocoaPods support is still on its way!

**Comment by amajeedmuazu** [comment]
Add the folder "VimeoNetworking/VimeoNetworking/" that contains the 'Sources' and 'Resources' folder somewhere in your Swift (3) Xcode project then do the following :-

Get **AFNetworking** as it is a dependency (pod install available)
Get **VIMObjectMapper** as it is a dependency (pod install available)

Next in your objective-c bridging header, import VimeoNetworking.h 
like this. : `#import "VimeoNetworking.h"` and not `#import <VimeoNetworking/VimeoNetworking.h>`

Next open  _VimeoNetworking/Sources/VimeoNetworking.h_ file, replace all imports with the quotation format. e.g. 
`#import <VimeoNetworking/VIMAccount.h>`  to  `#import "VIMAccount.h"` 
`#import <VimeoNetworking/VIMActivity.h>`  to  `#import "VIMActivity.h"` 
 ...

Next, either build so the build errors will point you to files containing 
`#import <VimeoNetworking/VimeoNetworking.h>`
or find them manually and replace the import with the quotation format 
`#import "VimeoNetworking.h"`

Next, Open the file _VimeoNetworking/Sources/Models/PlayProgress.swift_ :
   Replace the class declaration
  `public class PlayProgress : VIMModelObject` 
with 
  `@objc open class PlayProgress : VIMModelObject`

Next, Open the file _VimeoNetworking/Sources/Models/VIMVideo.m_ and _VimeoNetworking/Sources/Models/VIMVideoPlayRepresentation.h_
  Replace the import 
  `#import <VimeoNetworking/VimeoNetworking-Swift.h>` 
with 
  `#import "YourProjectNameHere-Swift.h"` 
(Use you project name instead, don't worry about not having such a file, just do it, it just works )


Now build and it should build successfully.
