### ISSUE TITLE
Doing Pod Install Not Working.

### ISSUE THREAD

**Issue by eman6576** [vimeo/VimeoNetworking#74]
Hi,

When doing a pod install using `pod 'VimeoNetworking', '1.1'` Cocoapods complains that it can't find a specification. I tried doing `pod 'VimeoNetworking'` without specifying the version number and that doesn't work either. Is the documentation wrong for the version to use since I looked at the podspec and the version there was 0.0.1. Thanks.

**Comment by jasonhawkins** [comment]
Hey Emanuel, thanks for creating an issue. VimeoNetworking's CocoaPods integration is currently broken, but getting it working is on our list of priorities for the near future. We're in the middle of a large codebase migration at the moment, which is part of the reason for the delay. 

Right now the only way to integrate VimeoNetworking into your project is to drag the files in manually. I realize that's… not ideal : / 

At the moment it's the best we can do until we can be a good CocoaPods citizen again – something we are very much looking forward to. Thanks again for opening an issue. I'm going to close it for now, but we're working on it!

**Comment by eman6576** [comment]
Oh alright didn't know. Thank you.
