### ISSUE TITLE
Vimeo Pro members can NOT access playback URLs for Vimeo videos which are created by others

### ISSUE THREAD

**Issue by wangbourne** [vimeo/VimeoNetworking#79]
Here [https://github.com/vimeo/VIMVideoPlayer](url)
It describes: "Vimeo Pro members can access playback URLs for Vimeo videos using the Vimeo API. Playback URLs are only included in the response object if the requesting account is a Vimeo Pro account.". 

I did a test here and found:
1.  I can get playback URLs if the videos are created by myself, and I can play via VIMVideoPlayer. I noticed that there's a token in the url, will this token expire?  
2. I could **NOT** get playback URLs if the video are **NOT** created by myself

Is that true?

**Comment by hash3r** [comment]
I would like to support topic starter question.
Is it possible to play public video files created by other users?

**Comment by jasonhawkins** [comment]
Hooooo boy, this is an old one. Here are some answers:
1. Yes, the URLs will expire. You'd need to fetch the video object again to get updated URLs for the video files.
2. That is correct, video files for other users are not accessible without registering as a partner here: https://www.vimeopartnernetwork.com

Which should also answer @hash3r's question – you would need to register as a partner to access video files created by other users.
